provider:
  name: faas
  gateway: http://localhost:8080

functions:
  upload-pipeline:
    lang: faasflow
    handler: ./upload-pipeline
    image: s8sg/upload-pipeline:latest
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
    environment_file:
      - upload-pipeline.yml


  upload-pipeline-async:
    lang: faasflow
    handler: ./upload-pipeline-async
    image: s8sg/upload-pipeline-async:latest
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
      s3_url: "minio:9000"
      s3_bucket: "faasflow"
      s3_tls: false
      secret_mount_path: "/var/run/secrets/"
    environment_file:
      - upload-pipeline-async.yml
    secrets:
      - s3-secret-key
      - s3-access-key 

  colorization:
    lang: dockerfile
    handler: ./faas-colorization
    image: s8sg/colorization:latest
    environment:
      read_timeout: 60
      write_timeout: 60

  image-resizer:
    lang: dockerfile
    handler: ./cdn_faas/ResizeImage
    image: s8sg/resizer:latest
    environment:
      read_timeout: 60
      write_timeout: 60

  facedetect:
    lang: go-opencv
    handler: ./facedetect-openfaas/facedetect
    image: s8sg/facedetect:latest
    environment:
      input_mode: "image"
      output_mode: "json"

  file-storage:
    lang: dockerfile
    handler: ./cdn_faas/file_storage
    image: s8sg/file-storage:latest
    environment:
      read_timeout: 60
      write_timeout: 60
